{
    "name": "Inventory Reports : Addis Systems",
    "version": "17.0.1.0",
    "sequence": 55,
    "summary": "Addis Systems Inventory/Stock Basic Reports",
    "description": """
        This Module is developed by Addis Systems for Basic Inventory/Stock Reports.
            ========================================
    """,
    "category": "Addis Systems/Inventory",
    "author": "Addis Systems/Beruk W.",
    "website": "https://www.addissystems.et/",
    "license": "LGPL-3",
    "depends": ["addis_systems_stock_base", "addis_systems_stock","stock_delivery","product_expiry", "report_xlsx"],
    "external_dependencies": {"python": ["pulsar-client", "avro", "avro-schema"]},
    "data": [
        "security/ir.model.access.csv",
        "reports/AddisSystemStockCardReport.xml",
        "reports/inventory_serial_stock_card__report.xml",
        "reports/AddisSystemsStockFiscalYearBeginningBalanceReport.xml",
        "reports/inventory_stock_balance_report.xml",
        "wizard/AddisSystemsStockCardView.xml",
        "wizard/inventory_serial_Stock_card_view.xml",
        "wizard/inventory_summary_stock_balance.xml",
        "wizard/AddisSystemsStockFiscalYearBeginningBalanceReportView.xml",
        "reports/layouts.xml",
        "reports/attachement_design_picking_type_operation.xml",
        "reports/attachement_design_report_delivery_slip.xml",
        "reports/inventory_produt_expiry.xml",
        "reports/inventory_template_summarized_by_customer.xml",
        "reports/inventory_template_summarized_by_product_category.xml",
        "reports/inventory_template_summarized_by_date.xml",
        "reports/inventory_template_summarized_by_trxname.xml",
        "reports/inventory_template_summarized_bincard.xml",
        "reports/transaction_name_in_all.xml",
        "reports/reports.xml",
        "wizard/inventory_product_expiry_wizard.xml",
        "wizard/inventory_summarized_by_customer.xml",
        "wizard/inventory_summary_product_category.xml",
        "wizard/inventory_summary_product_date.xml",
        "wizard/inventory_summary_product_trxnname.xml",
        "wizard/inventory_summary_product_bincard.xml",
        "views/inventory_report_views.xml",
        #"views/report_stock_move_serial_stock_card_views.xml"
    ],
    "assets": {
        "web._assets_primary_variables": [],
        "web._assets_backend_helpers": [],
        "web.assets_backend": [
            "addis_systems_stock_reports/static/src/xml/inventory_product_expiry.xml",
            "addis_systems_stock_reports/static/src/js/inventory_product_expiry.js",
            "addis_systems_stock_reports/static/src/css/drop_down.css",
            "addis_systems_stock_reports/static/src/xml/AddisSystemsQwebTemplateInherited.xml"
        ],
        "web.assets_frontend": [],
        "web.assets_tests": [],
        "web.qunit_suite_tests": [],
        "web.assets_qweb": [],
    },
    "demo": [],
    "installable": True,
    "price": 49.99,
    "currency": "ETB",
    "application": True,
    'auto_install': ["addis_systems_stock_base", "addis_systems_stock"],
}
