{
    "name": "Addis Systems Sales Reports",
    "version": "17.0.1.0",
    "sequence": 65,
    "summary": "Addis Systems Sales Basic Reports",
    "description": """
        This Module is developed by Addis Systems for Basic Sales Reports.
            ========================================
    """,
    "category": "Addis Systems/Sales",
    "author": "Addis Systems/Beruk W.",
    "website": "https://www.addissystems.et/",
    "license": "LGPL-3",
    "depends": ["addis_systems_sales_base", "addis_systems_sales"],
    "external_dependencies": {"python": ["pulsar-client", "avro", "avro-schema"]},
    "data": [
        'security/ir.model.access.csv',
        'views/addis_systems_header_footer_template_cash_credit_refund.xml',
        'views/addis_systems_header_footer_template_date.xml',
        'views/addis_systems_header_footer_template_category.xml',
        'views/addis_systems_header_footer_template_user.xml',
        'views/addis_systems_header_footer_template_detail.xml',
        'views/addis_systems_header_footer_template_goods.xml',
        'views/addis_systems_header_footer_template_profitability.xml',
        'views/addis_systems_header_footer_template_cash_credit_refund.xml',
        'views/addis_systems_header_footer_template_sales_summary_ongoing_running.xml',
        'views/addis_systems_header_footer_template_sales_summary_product_summary.xml',
        'views/addis_systems_header_footer_template_category_cash_invoice.xml',
        'views/addis_systems_header_footer_template_cash_credit_refund_cashier_date.xml',
        'views/addis_systems_header_footer_template_category_cash_credit_refund.xml',
        'views/addis_systems_header_footer_template_customer_type.xml',

        'wizard/sales_summary_cash_credit_refund.xml',
        'wizard/sales_summary_report_by_date.xml',
        'wizard/sales_summary_report_by_category.xml',
        'wizard/sales_summary_report_by_customer.xml',
        'wizard/sales_summary_report_by_user.xml',
        'wizard/sales_summary_report_by_detail.xml',
        'wizard/sales_summary_report_by_goods.xml',
        'wizard/sales_summary_report_by_profitabiliy.xml',
        'wizard/sales_summary_cash_credit_refund.xml',
        'wizard/sales_summary_ongoing.xml',
        'wizard/sales_summary_product_summary_report.xml',
        'wizard/sales_summary_report_by_category_sales_cash_invoice.xml',
        'wizard/sales_summary_cash_credit_refund_cashier_date.xml',
        'wizard/sales_summary_report_by_category_cash_credit_refund.xml',
        'wizard/sales_summary_report_by_customer_type.xml',
        'wizard/sales_summary_report_by_category_general.xml',

        'report/addis_sales_summary_report_date.xml',
        'report/addis_sales_summary_report_category.xml',
        'report/addis_sales_summary_report_customer.xml',
        'report/addis_sales_summary_report_user.xml',
        'report/addis_sales_summary_report_detail.xml',
        'report/addis_sales_summary_report_profitability.xml',
        'report/addis_sales_summary_report_goods.xml',
        'report/addis_sales_report_cash_credit_refund.xml',
        'report/addis_sales_summary_report_onging_running.xml',
        'report/addis_sales_summary_report_product_summary.xml',
        'report/addis_sales_summary_report_category_cash_invoice.xml',
        'report/addis_sales_report_cash_credit_refund_cashier_date.xml',
        'report/addis_sales_summary_report_category_cash_credit_refund.xml',
        'report/addis_sales_summary_report_customer_type.xml',
        'report/addis_sales_summary_report_category_general.xml'
    ],
    "assets": {
        "web._assets_primary_variables": [],
        "web._assets_backend_helpers": [],
        "web.assets_backend": [],
        "web.assets_frontend": [],
        "web.assets_tests": [],
        "web.qunit_suite_tests": [],
        "web.assets_qweb": [],
    },
    "demo": [],
    "installable": True,
    "price": 49.99,
    "currency": "ETB",
    "application": True,
    'auto_install': ["addis_systems_sales_base", "addis_systems_sales"],
}
